sudo: false
language: python
python:
  - 3.6
install:
  - pip install flake8
  - pip install isort
  - pip install -e .
script:
  - flake8 .
  - isort --check-only --diff --quiet

notifications:
  email: false
